// Generated by scripts/design/generate-experience-tokens.mjs.
package top.sywyar.pixivdownload.gui.bootstrap;

record StartupSplashColors(int surface, int text, int secondaryText, int accent, int border) {
    private static final StartupSplashColors light = new StartupSplashColors(0xFFFFFF, 0x1D1D1F, 0x616166, 0x1E6EF4, 0x85858B);
    private static final StartupSplashColors dark = new StartupSplashColors(0x242426, 0xF5F5F7, 0xB5B5BB, 0x5CB8FF, 0x85858B);
    private static final StartupSplashColors highContrastLight = new StartupSplashColors(0xFFFFFF, 0x000000, 0x333333, 0x185ECF, 0x555555);
    private static final StartupSplashColors highContrastDark = new StartupSplashColors(0x000000, 0xFFFFFF, 0xDDDDDD, 0x5CB8FF, 0xBBBBBB);

    static StartupSplashColors forAppearance(StartupAppearance appearance) {
        return appearance.highContrast()
                ? (appearance.dark() ? highContrastDark : highContrastLight)
                : (appearance.dark() ? dark : light);
    }
}
