spring.application.name=PixivDownload
server.port=6999
server.servlet.context-path=/
download.root-folder=pixiv-download
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB