package top.sywyar.pixivdownload.config;

import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.nio.charset.StandardCharsets;

/**
 * 代理自动配置（PAC）端点：仅本地客户端可获取（由 {@code AuthFilter} 做本地放行 + 本地校验）。
 *
 * <p>用途：让浏览器无需开启系统级 system proxy，也能让「网页版 Pixiv」走后端在
 * {@link ProxyConfig} 中指定的同一个代理（默认 {@code 127.0.0.1:7890}）。生成的 PAC 只为
 * Pixiv 相关域名返回 {@code PROXY host:port}，其余流量一律 {@code DIRECT} 直连，互不影响。
 *
 * <p>使用方式：在系统 / 浏览器的「自动代理配置脚本（PAC）URL」处填入本端点地址（如
 * {@code http://localhost:{port}/proxy.pac}），即可永久关闭 Clash 的 system proxy，
 * 由本配置统一决定 Pixiv 是否走代理；{@code ProxyConfig} 改动（含热重载）会自动反映到 PAC 内容。
 */
@RestController
@RequiredArgsConstructor
public class ProxyPacController {

    /** PAC 文件的标准 MIME 类型。 */
    private static final MediaType PAC_MEDIA_TYPE =
            new MediaType("application", "x-ns-proxy-autoconfig", StandardCharsets.UTF_8);

    private final ProxyConfig proxyConfig;

    @GetMapping("/proxy.pac")
    public ResponseEntity<String> proxyPac() {
        return ResponseEntity.ok()
                .contentType(PAC_MEDIA_TYPE)
                .header(HttpHeaders.CACHE_CONTROL, "no-store")
                .body(buildPac());
    }

    /**
     * 依据当前 {@link ProxyConfig} 生成 PAC 脚本：代理开启且 host/port 合法时，Pixiv 域名走该代理；
     * 否则全部直连（等价于关闭本特性，Pixiv 网页将无法直接访问——与「代理已禁用」语义一致）。
     */
    private String buildPac() {
        String host = proxyConfig.getHost();
        int port = proxyConfig.getPort();
        boolean usable = proxyConfig.isEnabled() && host != null && !host.isBlank() && port > 0;
        // host 来自管理员配置，PAC 中以 JS 字符串字面量出现，做最小转义避免破坏脚本。
        String proxyDirective = usable
                ? "\"PROXY " + escapeJs(host) + ":" + port + "; DIRECT\""
                : "\"DIRECT\"";
        return """
                // Generated by PixivDownloader — keep web Pixiv on the backend-configured proxy
                // without enabling a system-wide proxy. Edit the proxy in config.yaml / GUI instead.
                function FindProxyForURL(url, host) {
                  if (shExpMatch(host, "pixiv.net") ||
                      shExpMatch(host, "*.pixiv.net") ||
                      shExpMatch(host, "*.pximg.net") ||
                      shExpMatch(host, "*.pixiv.org") ||
                      shExpMatch(host, "*.fanbox.cc") ||
                      shExpMatch(host, "*.pixivision.net")) {
                    return %s;
                  }
                  return "DIRECT";
                }
                """.formatted(proxyDirective);
    }

    private static String escapeJs(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
