package top.sywyar.pixivdownload.douyin.client;

public enum DouyinClientErrorCode {
    INVALID_URL,
    INVALID_SHORT_URL,
    SHORT_LINK_UNRESOLVED,
    NETWORK_TIMEOUT,
    HTTP_FORBIDDEN,
    HTTP_RATE_LIMITED,
    REDIRECT_LOOP,
    NON_DOUYIN_TARGET,
    LOGIN_OR_VERIFY_PAGE,
    UNSUPPORTED_FINAL_URL,
    UNSUPPORTED_CONTENT,
    MEDIA_URL_MISSING,
    DOWNLOAD_SIZE_MISMATCH,
    SIGNATURE_REQUIRED,
    RATE_LIMITED,
    COOKIE_REQUIRED,
    COOKIE_MISSING_FIELDS,
    COOKIE_EXPIRED,
    REGION_RESTRICTED,
    PERMISSION_DENIED,
    NETWORK_ERROR,
    CANCELLED
}
