plugin.credential.key.profile=open-source
plugin.credential.key.current-base64=ieiuDoVetH5W1984VOMLG2rBJT53zzBQHK/HrG+0Moc=
plugin.credential.key.open-source-fallback-base64=ieiuDoVetH5W1984VOMLG2rBJT53zzBQHK/HrG+0Moc=
