package top.sywyar.pixivdownload.core.metadata.novel;

public record NovelRecord(
        long novelId,
        String title,
        String folder,
        int count,
        String extensions,
        long time,
        Integer xRestrict,
        Boolean isAi,
        Long authorId,
        String description,
        Long fileName,
        Long fileAuthorNameId,
        Long seriesId,
        Long seriesOrder,
        Integer wordCount,
        Integer textLength,
        Integer readingTimeSeconds,
        Integer pageCount,
        Boolean isOriginal,
        String xLanguage,
        String rawContent,
        String coverExt,
        boolean deleted
) {
    public NovelRecord(long novelId,
                       String title,
                       String folder,
                       int count,
                       String extensions,
                       long time,
                       Integer xRestrict,
                       Boolean isAi,
                       Long authorId,
                       String description,
                       Long fileName,
                       Long fileAuthorNameId,
                       Long seriesId,
                       Long seriesOrder,
                       Integer wordCount,
                       Integer textLength,
                       Integer readingTimeSeconds,
                       Integer pageCount,
                       Boolean isOriginal,
                       String xLanguage,
                       String rawContent,
                       String coverExt) {
        this(novelId, title, folder, count, extensions, time, xRestrict, isAi, authorId, description,
                fileName, fileAuthorNameId, seriesId, seriesOrder, wordCount, textLength,
                readingTimeSeconds, pageCount, isOriginal, xLanguage, rawContent, coverExt, false);
    }
}
